# Generated by Django 2.2.9 on 2020-01-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUserManager',
        ),
    ]
